export const ADD_GAME = 'ADD_GAME';
export const ADD_GAME_SUCCESS = 'ADD_GAME_SUCCESS';
export const ADD_GAME_FAILURE = 'ADD_GAME_FAILURE';
export const GET_GAME_LIST = 'GET_GAME_LIST';
export const GET_GAME_LIST_SUCCESS = 'GET_GAME_LIST_SUCCESS';
export const GET_GAME_LIST_FAILURE = 'GET_GAME_LIST_FAILURE';

enum Types {
  ADD_GAME,
  ADD_GAME_SUCCESS,
  ADD_GAME_FAILURE,
  GET_GAME_LIST,
  GET_GAME_LIST_SUCCESS,
  GET_GAME_LIST_FAILURE
};

export default Types;
